---
version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: mvlab
      POSTGRES_PASSWORD: z1x2c3
      POSTGRES_DB: db1
      PGDATA: /data/postgres
      TZ: Europe/Minsk
    volumes:
      - postgres:/data/postgres
      #  - ./volume/DB/:/data/postgres
    ports:
      - "15432:5432"
    networks:
      mvlab_network:
        ipv4_address: 10.0.0.2

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.0
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-nr@mvlab.by}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-z1x2c3}
      TZ: Europe/Minsk

    volumes:
      - pgadmin:/root/.pgadmin
      # - ./volume/pgadmin_data/:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      mvlab_network:
        ipv4_address: 10.0.0.3

    restart: unless-stopped

  nginx:
    container_name: nginx_server
    image: nginx
    # restart: always
    environment:
      - TZ=Europe/Minsk
    volumes:
      - ./temp_data:/usr/share/nginx/html
      # - web_data:/usr/share/nginx/html
    ports:
      - "81:80"
    networks:
      mvlab_network:
        ipv4_address: 10.0.0.4

  ndr:
    container_name: ndr
    image: nodered/node-red:latest
    # restart: always
    environment:
      - TZ=Europe/Minsk
    ports:
      - "1880:1880" #web
      - "1883:1883" #mqtt
    volumes:
      - ndr_data:/data
#      - ./node-red:/data
    networks:
      mvlab_network:
        ipv4_address: 10.0.0.8

  web:
    container_name: web_server
    build: web
    # command: bash -c "npm install && npm run dev"
    command: bash -c "
      npm install &&
      npm run dev"
    volumes:
      - ./web:/code
      # - web_data:/code/
    ports:
      - "80:80"
    networks:
      mvlab_network:
        ipv4_address: 10.0.0.5
    # restart: unless-stopped

  opc:
    container_name: opc_server
    build: opc
    command: python3 main.py
    # restart: always
    depends_on:
      - postgres
      - api
    volumes:
      - ./opc:/code
    ports:
      - 5001:5001
    networks:
      mvlab_network:
        ipv4_address: 10.0.0.6

  api:
    container_name: api_server
    build: api
    # restart: always
    command:
      bash -c
      "
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:50001"
      # gunicorn --bind 0.0.0.0:50001 project_v_0_0_1.wsgi"
    depends_on:
      - postgres
    volumes:
      - ./api:/code
    ports:
      - 50001:50001
    networks:
      mvlab_network:
        ipv4_address: 10.0.0.7
      

networks:
  mvlab_network:
    driver: bridge
    enable_ipv6: false
    ipam:
      # driver: default
      config:
        - subnet: 10.0.0.0/24
        # - gateway: '10.0.0.1'

volumes:
  postgres:
  pgadmin:
  web_data:
  ndr_data:
#     api_data:
#     opc_data:
